-- Hand-written (not generated by drizzle-kit). Runs after 0015's backfill populates
-- facilities.organization_id, facilities.facility_name, facilities.timezone, and
-- rooms.facility_id for the pre-existing seeded rows. Asserting NOT NULL here before
-- backfill would fail against that existing data -- the exact ordering hazard this
-- task's migration split exists to avoid (see task-1-report.md).
ALTER TABLE "facilities" ALTER COLUMN "organization_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "facilities" ALTER COLUMN "facility_name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "facilities" ALTER COLUMN "timezone" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "rooms" ALTER COLUMN "facility_id" SET NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "rooms_facility_id_name_uniq" ON "rooms" USING btree ("facility_id","name");
