-- Hand-written (not generated by drizzle-kit). Backfills `item_code` for
-- pre-existing inventory_items rows: generates a 4-hex-char code per row
-- (matches generateShortId()'s shape in artifacts/api-server/src/lib/utils.ts),
-- re-rolling on same-facility collision via the WHERE NOT EXISTS retry loop.
-- Pilot data is small, so this converges immediately in practice.
--
-- Leaves item_code nullable (new rows always get one via the app-layer retry
-- loop in POST /inventory / onConflictDoNothing on the composite unique index
-- added in 0021). Same established convention as cycles.short_id /
-- shipments.short_id: app-enforced-non-null via the insert path, not a
-- DB-level NOT NULL.
DO $$
DECLARE
  r RECORD;
  candidate TEXT;
BEGIN
  FOR r IN SELECT id, facility_id FROM inventory_items WHERE item_code IS NULL LOOP
    LOOP
      candidate := lpad(to_hex(floor(random() * 65536)::int), 4, '0');
      EXIT WHEN NOT EXISTS (
        SELECT 1 FROM inventory_items
        WHERE facility_id = r.facility_id AND item_code = candidate
      );
    END LOOP;
    UPDATE inventory_items SET item_code = candidate WHERE id = r.id;
  END LOOP;
END $$;
