-- Hand-written (not generated by drizzle-kit). Backfills `seed_lots.facility_id`
-- to the single pilot facility (only one has ever existed — same reasoning as
-- 0019), then enforces NOT NULL now that every row has a value.
UPDATE seed_lots SET facility_id = (SELECT id FROM facilities ORDER BY id LIMIT 1)
  WHERE facility_id IS NULL;--> statement-breakpoint
ALTER TABLE "seed_lots" ALTER COLUMN "facility_id" SET NOT NULL;
