-- Hand-written (not generated by drizzle-kit) -- same convention as
-- 0019_backfill_tenancy_scoping.sql and 0024_seed_lots_qr_code_backfill_and_contract.sql's
-- backfill half.
--
-- At the moment this migration runs, POST /facilities's pre-TEN-008 409 gate
-- (facilities.ts's AlreadyHasFacilityError, removed in this same milestone's
-- Task 4) has never allowed a second facility per organization -- so each
-- user's organization matches at most exactly one facilities row, never more.
-- A user with no organization yet (wizard still in progress, never reached W2's
-- POST /facilities) correctly stays facility_id IS NULL: that row IS the
-- in-progress wizard run Task 3's partial unique index protects.
--
-- Deterministic tie-break (lowest id wins): the migration itself does not
-- assume the one-facility-per-org gate holds. If an organization ever holds
-- 2+ facilities at migration-run time, an unordered JOIN would pick an
-- arbitrary one (plan-dependent). We defend against that exact ambiguity by
-- using `LATERAL ... ORDER BY id LIMIT 1`, i.e. lowest-id-facility-wins --
-- the same established backfill convention this repo uses in
-- 0019_backfill_tenancy_scoping.sql ((SELECT id FROM facilities ORDER BY id
-- LIMIT 1)) and 0024_seed_lots_qr_code_backfill_and_contract.sql, for this
-- identical ambiguity class. The WHERE clause still requires
-- u.organization_id IS NOT NULL, so org-less in-progress wizard rows are
-- untouched.
UPDATE wizard_progress wp
SET facility_id = f.id
FROM users u
JOIN LATERAL (
  SELECT id FROM facilities WHERE organization_id = u.organization_id ORDER BY id LIMIT 1
) f ON true
WHERE wp.user_id = u.id
  AND wp.facility_id IS NULL
  AND u.organization_id IS NOT NULL;
