-- Hand-written (not generated by drizzle-kit) -- same convention as
-- 0019_backfill_tenancy_scoping.sql and 0024's backfill half.
--
-- At the moment this migration runs, POST /facilities's pre-TEN-008 409 gate
-- (facilities.ts's AlreadyHasFacilityError, removed in this same milestone's
-- Task 4) has never allowed a second facility per organization -- so this
-- JOIN matches at most exactly one facilities row per user, never more. A
-- user with no organization yet (wizard still in progress, never reached W2's
-- POST /facilities) correctly stays facility_id IS NULL: that row IS the
-- in-progress wizard run Task 3's partial unique index protects.
UPDATE wizard_progress wp
SET facility_id = f.id
FROM users u
JOIN facilities f ON f.organization_id = u.organization_id
WHERE wp.user_id = u.id
  AND wp.facility_id IS NULL
  AND u.organization_id IS NOT NULL;
