-- Hand-written (not generated by drizzle-kit) -- same convention as 0020's
-- contract half. Drops the old per-user-only uniqueness (wrong once a user
-- can have one wizard_progress row per facility) and replaces it with the
-- two indexes the schema now declares: a composite unique for real
-- facilities, plus a partial unique (facility_id IS NULL) so at most one
-- in-progress "which facility am I even creating" run can exist per user at
-- a time.
DROP INDEX "wizard_progress_user_id_uniq";--> statement-breakpoint
CREATE UNIQUE INDEX "wizard_progress_user_id_facility_id_uniq" ON "wizard_progress" USING btree ("user_id","facility_id");--> statement-breakpoint
CREATE UNIQUE INDEX "wizard_progress_user_id_no_facility_uniq" ON "wizard_progress" USING btree ("user_id") WHERE "wizard_progress"."facility_id" IS NULL;
